config/routes.rb
Rails.application.routes.draw do
  #EXHIBITIONS
  resources :exhibitions do
    resources :visits
  end
  get 'exhibitions/:id/manage' => 'exhibitions#manage', :as => :manage_exhibition

  #PLACES
  resources :places

  # USERS
  devise_for :users

  devise_scope :user do
  	get "/signin" => "devise/sessions#new"
  	get "/signup" => "devise/registrations#new"
  end
  resources :users

  get '/demands', to: 'users#demands'

  # PAGE
  get '/dev', to: 'pages#index'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  #ROOT PAGE
  if Rails.env.production?
    root 'pages#index'
  else
    root 'pages#index'
  end

end

app/models/visit.rb
# == Schema Information
#
# Table name: visits
#
#  id            :integer          not null, primary key
#  coming_at     :datetime
#  user_id       :integer
#  exhibition_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Visit < ActiveRecord::Base
  belongs_to :user
  belongs_to :exhibition

  validates :exhibition, presence: true
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /exhibitions/:exhibition_id/visits/new
  def new
    @exhibition = Exhibition.find(params[:exhibition_id])
    @visit = Visit.new

  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @exhibition       = Exhibition.find(params[:exhibition_id])
    @visit            = Visit.new(visit_params)
    if @exhibition.visits.count >= @exhibition.capacity
      respond_to do |format|
        format.html { redirect_to exhibition_path(params[:exhibition_id]), notice: 'Capacité du lieu atteinte. Impossible de vous y inscrire' }
      end
    else
      if @visit.coming_at < @exhibition.opening_at
        respond_to do |format|
          format.html { redirect_to exhibition_path(params[:exhibition_id]), notice: "Votre date de visite doit être comprise dans les dates d'ouverture de l'exposition" }
        end
      else
        if @visit.coming_at >= @exhibition.closing_at
          respond_to do |format|
            format.html { redirect_to exhibition_path(params[:exhibition_id]), notice: "Votre date de visite doit être comprise dans les dates d'ouverture de l'exposition" }
          end
        else
          @visit.exhibition = @exhibition
          @visit.user       = current_user

          respond_to do |format|
            if @visit.save
              UserNotifier.send_registration_email(@visit).deliver_later

              format.html { redirect_to exhibition_path(params[:exhibition_id]), notice: 'Visit was successfully created.' }
              format.json { render :show, status: :created, location: @visit }
            else
              format.html { render :new }
              format.json { render json: @visit.errors, status: :unprocessable_entity }
            end
          end
        end
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:coming_at, :user, :exhibition)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= simple_form_for(@visit, url: @visit.new_record? ? exhibition_visits_path(exhibition_id: @exhibition.id) : exhibition_visit_path(@visit)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :coming_at %>

  <!--  <%= f.input :user %> -->


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/visits/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Exposition</th>
      <th>Date et heure d'arrivée</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <div class="col-md-1"><td><%= visit.exhibition %></td></div>
        <div class="col-md-11"><td><%= visit.coming_at %></td></div>
        <td><%= link_to 'Voir plus', exhibition_visit_path(exhibition_id: 1) %></td>
      <!--  <td><%#= link_to 'Editer', edit_exhibition_visit_path(visit) %></td>-->
      <!--  <td><%#= link_to 'Destroy', exhibition_visit_path(exhibition_id: 1), method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form' %>

<%= link_to 'Voir plus', @visit %> |
<%= link_to 'Retour', exhibitions_visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visits</h1>

<table>
  <thead>
    <tr>
      <th>Coming at</th>
      <th>User</th>
      <th>Exhibition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.coming_at %></td>
        <td><%= visit.user %></td>
        <td><%= visit.exhibition %></td>
        <td><%= link_to 'Voir plus', exhibition_visit_path(id: visit.id, exhibition_id: visit.exhibition_id) %></td>
        <td><%= link_to 'Editer', edit_exhibition_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', exhibition_visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_exhibition_visit_path %>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= render 'form' %>

<%= link_to 'Retour', exhibitions_visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coming at:</strong>
  <%= @visit.coming_at %>
</p>

<p>
  <strong>User:</strong>
  <%= @visit.user %>
</p>

<p>
  <strong>Exhibition:</strong>
  <%= @visit.exhibition %>
</p>

<%= link_to 'Retour', user_path(current_user) %>