config/routes.rb
Rails.application.routes.draw do
  #EXHIBITIONS
  resources :exhibitions do
    resources :visits
  end
  get 'exhibitions/:id/manage' => 'exhibitions#manage', :as => :manage_exhibition

  #PLACES
  resources :places

  # USERS
  devise_for :users

  devise_scope :user do
  	get "/signin" => "devise/sessions#new"
  	get "/signup" => "devise/registrations#new"
  end
  resources :users

  get '/demands', to: 'users#demands'

  # PAGE
  get '/dev', to: 'pages#index'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  #ROOT PAGE
  if Rails.env.production?
    root 'pages#index'
  else
    root 'pages#index'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :biography, :email, :password, :current_password, :website) }
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<header>
  <div class='content'>
    <a class='logo' href='#' title='Texposou'></a>
    <nav class='left'>
      <ul>
        <li>
          <%= link_to 'Accueil', root_path %>
        </li>
        <li>
          <%= link_to 'À propos', about_path %>
        </li>
        <li>
          <%= link_to 'Contact', contact_path %>
        </li>
      </ul>
    </nav>
    <nav class='right'>
      <ul>
        <li>
          <% if !user_signed_in? %>
            <%= link_to 'Proposer un lieu', signin_path, class: "new-place" %>
          <% else %>
            <%= link_to 'Proposer un lieu', new_place_path, class: "new-place" %>
          <% end %>
        </li>
        <li class='account'>
          <% if !user_signed_in? %>
            <a href='#'>Mon compte</a>
            <ul class='menu-account'>
              <li>
                <%= link_to 'Connexion', signin_path %>
              </li>
              <li>
                <%= link_to 'Inscription', signup_path %>
              </li>
            </ul>
          <% else %>
            <%= link_to current_user, "#"  %>
            <ul class='menu-account'>
              <li>
                <%= link_to "Profil", current_user %>
              </li>
              <li>
                <%= link_to 'Paramètres',edit_user_registration_path %>
              </li>
              <li>
                <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>