config/routes.rb
Rails.application.routes.draw do
  #EXHIBITIONS
  resources :exhibitions do
    resources :visits
  end
  get 'exhibitions/:id/manage' => 'exhibitions#manage', :as => :manage_exhibition

  #PLACES
  resources :places

  # USERS
  devise_for :users

  devise_scope :user do
  	get "/signin" => "devise/sessions#new"
  	get "/signup" => "devise/registrations#new"
  end
  resources :users

  get '/demands', to: 'users#demands'

  # PAGE
  get '/dev', to: 'pages#index'
  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  #ROOT PAGE
  if Rails.env.production?
    root 'pages#index'
  else
    root 'pages#index'
  end

end

app/views/layouts/_topbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Texposou', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', places_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Contact', contact_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><% if user_signed_in? %><%= current_user %><% else %>Account<% end %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if !user_signed_in? %>
                <li><%= link_to 'Sign in', signin_path %></li>
                <li><%= link_to 'Sign up', signup_path %></li>
              <% else %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to 'Account',edit_user_registration_path %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Texposou</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'application/header' %>
  
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>